<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Birthdate</name>
   <tag></tag>
   <elementGuidId>00260e45-d3d6-4cb6-80c1-61aba7334b9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='birthdateLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#birthdateLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#formBreadcrumb >> internal:text=&quot;Birthdate&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>83c9040a-8a1e-4b51-8a2a-c797637a9c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthdateLabel</value>
      <webElementGuid>1124e819-f18d-47c0-8aba-4c4f3304a176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Birthdate</value>
      <webElementGuid>f1e0d76c-156c-4311-b286-61c89fe7252b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formBreadcrumb&quot;)/li[@class=&quot;doing&quot;]/ul[1]/li[@class=&quot;question-legend&quot;]/span[@id=&quot;birthdateLabel&quot;]</value>
      <webElementGuid>68b2ec31-1867-4a35-9d32-f23a5b065c9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='birthdateLabel']</value>
      <webElementGuid>00afd95f-7ec7-41ad-bf20-20c9ed235349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='formBreadcrumb']/li/ul/li[3]/span</value>
      <webElementGuid>76f44a8e-426d-4284-a305-3294c9a73377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::span[1]</value>
      <webElementGuid>6b01a98f-dd34-4e60-ad5a-9b02e4a02676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::span[2]</value>
      <webElementGuid>0f0d7247-c618-4f1a-af20-5cd41dc190ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Info'])[1]/preceding::span[1]</value>
      <webElementGuid>7783b631-ee72-4ad8-a5c0-46e1e3f72298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::span[2]</value>
      <webElementGuid>65352fb7-54d4-4cf6-a162-b93421703136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Birthdate']/parent::*</value>
      <webElementGuid>f9372621-dbc1-43fe-a4d0-3dbe75b194f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/span</value>
      <webElementGuid>61ceac6d-04ef-4eee-adb2-62358415ef39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'birthdateLabel' and (text() = 'Birthdate' or . = 'Birthdate')]</value>
      <webElementGuid>4fb3eae8-e6d2-41f8-815d-a93acd98ef47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
